substitutions:
  devicename: grow-tent-monitor
  hostname: grow-tent-monitor
  friendlyname: "Grow Tent Monitor"
  board: esp32-s3-devkitc-1
  framework_type: arduino
  api_encryption_key: !secret api_encryption_key
  ota_password: !secret ota_update_key

esphome:
  name: ${hostname}
  friendly_name: ${friendlyname}
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
    board_build.f_cpu: 240000000L
  libraries:
    - Wire
    - FS
    - SPIFFS
    - m5stack/M5Unified

external_components:
  - source:
      type: local
      path: ../my_components
    components:
      - grow_env_monitor
      - m5cores3_display
      - m5cores3_touch
      - board_m5cores3
      - m5cores3_power
      - scd4x_stats
      - scd4x_alerts
      - mlx90640

esp32:
  board: ${board}
  flash_size: 16MB
  framework:
    type: ${framework_type}

logger:
  level: VERY_VERBOSE
  logs:
    api: WARN
    wifi: WARN
    json: WARN
    wifi_info: WARN
    api.service: WARN
    safe_mode: WARN
    esphome.ota: WARN
    binary_sensor: WARN
    homeassistant.binary_sensor: WARN
    number: WARN
    select: WARN
    switch: WARN
    text_sensor: WARN
    template.switch: WARN
    template.sensor: WARN
    template.number: WARN
    template.select: WARN
    template.binary_sensor: WARN
    template.text_sensor: WARN
    scd4x: WARN
    scd4x_stats: WARN
    scd4x_alerts: WARN
    m5cores3_touch: WARN
    sensor: WARN
    uptime.sensor: WARN
    wifi_signal.sensor: WARN
    mdns: WARN
    debug: WARN
    time: WARN
    gpio.binary_sensor: WARN
    logger: WARN
    wifi_esp32: WARN
    STA.cpp: WARN
    i2c.arduino: WARN
    esp32.preferences: WARN
    restart.button: WARN

debug:
  update_interval: 30s

api:
  encryption:
    key: "${api_encryption_key}"

ota:
  - platform: esphome
    password: "${ota_password}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  passive_scan: false
  power_save_mode: none
  ap:
    ssid: "Grow-Tent-Monitor"
    password: !secret fallback_hotspot_key

captive_portal:
web_server:
  version: 3
  port: 80
  sorting_groups:
    - id: environmental_monitoring
      name: "Environmental Monitoring"
      sorting_weight: 10
    - id: thermal_camera_group
      name: "Thermal Camera"
      sorting_weight: 20
    - id: environmental_alerts
      name: "Environmental Alerts"
      sorting_weight: 30
    - id: diagnostics
      name: "Diagnostics"
      sorting_weight: 40

web_server_base:
  id: my_web_server_base

i2c:
  sda: 2
  scl: 1
  scan: true

# Time synchronization with HA
time:
  - platform: homeassistant
    id: homeassistant_time

globals: []

# M5 Stack Hardware Support
board_m5cores3:
  id: m5_board

m5cores3_power:
  id: m5_power
  battery_sensor:
    name: "Battery Level"
    id: battery_level
  battery_present_sensor:
    name: "Battery Present"
    id: battery_present
  battery_charging_sensor:
    name: "Battery Charging"
    id: battery_charging

# MLX90640 thermal camera component (now self-contained)
mlx90640:
  id: thermal_camera
  refresh_rate: "16Hz" # Higher performance testing
  resolution: "18-bit" # Good balance of precision/speed
  pattern: "chess" # Better for even temperature distribution
  thermal_palette: "ironblack" # Most intuitive color mapping
  single_frame: false # Reduce motion artifacts
  update_interval: 2000 # Update every 2 seconds
  web_server:
    enable: true
    path: "/thermal.jpg"
    quality: 90
    web_server_base_id: my_web_server_base
  roi:
    enabled: false # Start disabled, user can enable via web interface
    center_row: 6 # Center of 24 rows (1-24 user range)
    center_col: 6 # Center of 32 cols (1-32 user range)
    size: 1 # 5x5 ROI (25 pixels)

  # Auto-generated temperature sensors
  temperature_sensors:
    min:
      name: "MLX90640 Min temp"
      id: mlx_min_temp
      web_server:
        sorting_group_id: thermal_camera_group
        sorting_weight: 10
    max:
      name: "MLX90640 Max temp"
      id: mlx_max_temp
      web_server:
        sorting_group_id: thermal_camera_group
        sorting_weight: 20
    avg:
      name: "MLX90640 Mean temp"
      id: mlx_mean_temp
      web_server:
        sorting_group_id: thermal_camera_group
        sorting_weight: 30
    roi_min:
      name: "MLX90640 ROI Min temp"
      id: mlx_roi_min_temp
      web_server:
        sorting_group_id: thermal_camera_group
        sorting_weight: 40
    roi_max:
      name: "MLX90640 ROI Max temp"
      id: mlx_roi_max_temp
      web_server:
        sorting_group_id: thermal_camera_group
        sorting_weight: 50
    roi_avg:
      name: "MLX90640 ROI Mean temp"
      id: mlx_roi_avg_temp
      web_server:
        sorting_group_id: thermal_camera_group
        sorting_weight: 60

  # Auto-generated user controls
  update_interval_control:
    name: "Thermal Update Interval"
    id: thermal_update_interval_number
    min_value: 100
    max_value: 30000
    step: 100
    web_server:
      sorting_group_id: thermal_camera_group
      sorting_weight: 80

  thermal_palette_control:
    name: "Thermal Color Palette"
    id: thermal_palette_select
    web_server:
      sorting_group_id: thermal_camera_group
      sorting_weight: 40

  roi_enabled_control:
    name: "ROI Enabled"
    id: roi_enabled_switch
    web_server:
      sorting_group_id: thermal_camera_group
      sorting_weight: 120

  roi_center_row_control:
    name: "ROI Center Row"
    id: roi_center_row_number
    min_value: 1
    max_value: 24
    step: 1
    web_server:
      sorting_group_id: thermal_camera_group
      sorting_weight: 90

  roi_center_col_control:
    name: "ROI Center Column"
    id: roi_center_col_number
    min_value: 1
    max_value: 32
    step: 1
    web_server:
      sorting_group_id: thermal_camera_group
      sorting_weight: 100

  roi_size_control:
    name: "ROI Size"
    id: roi_size_number
    min_value: 1
    max_value: 10
    step: 1
    web_server:
      sorting_group_id: thermal_camera_group
      sorting_weight: 110

  web_overlay_enabled_control:
    name: "Thermal Overlay Enable"
    id: thermal_overlay_switch
    web_server:
      sorting_group_id: thermal_camera_group
      sorting_weight: 70

grow_env_monitor:
  id: grow_monitor
  display_brightness: 70
  display_rotation: 3
  mlx90640_component: thermal_camera
  sensors:
    co2: co2_sensor
    temperature: temperature_sensor
    humidity: humidity_sensor
    thermal_min: mlx_min_temp
    thermal_max: mlx_max_temp
    thermal_avg: mlx_mean_temp
    roi_min: mlx_roi_min_temp
    roi_max: mlx_roi_max_temp
    roi_avg: mlx_roi_avg_temp
    light_sensor: grow_light_on
  # Connect to scd4x_alerts binary sensors for configurable thresholds
  temp_high_alert: temp_high_alert
  temp_low_alert: temp_low_alert
  humidity_high_alert: humidity_high_alert
  humidity_low_alert: humidity_low_alert
# M5 Stack Touch Support
m5cores3_touch:
  id: m5_touch
  on_touch:
    - logger.log:
        format: "Touch detected at (%d, %d)"
        args: ["touch.x", "touch.y"]
  on_release:
    - logger.log: "Touch released"
# End M5 Stack Hardware Support

sensor:
  - platform: scd4x
    id: co2_component
    co2:
      name: "CO2"
      id: co2_sensor
      web_server:
        sorting_group_id: environmental_monitoring
        sorting_weight: 10
    temperature:
      name: "Temperature"
      id: temperature_sensor
      web_server:
        sorting_group_id: environmental_monitoring
        sorting_weight: 20
    humidity:
      name: "Humidity"
      id: humidity_sensor
      web_server:
        sorting_group_id: environmental_monitoring
        sorting_weight: 30

  # System monitoring
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    update_interval: 60s
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 10

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 20

  # Debug/Performance monitoring
  - platform: debug
    free:
      name: "Free Memory"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 30
    block:
      name: "Heap Block Size"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 40
    loop_time:
      name: "Loop Time"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 50

scd4x_stats:
  id: co2_stats
  co2_sensor: co2_sensor
  temperature_sensor: temperature_sensor
  humidity_sensor: humidity_sensor
  time_id: homeassistant_time
  vpd:
    name: "VPD"
    id: vpd_sensor
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 40
  daily_max_co2:
    name: "Daily Max CO2"
    id: daily_max_co2
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 50
  daily_min_temp:
    name: "Daily Min Temperature"
    id: daily_min_temp
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 60
  daily_max_temp:
    name: "Daily Max Temperature"
    id: daily_max_temp
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 70
  co2_moving_avg:
    name: "CO2 Moving Average"
    id: co2_moving_avg
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 80
  temp_moving_avg:
    name: "Temperature Moving Average"
    id: temp_moving_avg
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 90

scd4x_alerts:
  id: co2_alerts
  co2_sensor: co2_sensor
  temperature_sensor: temperature_sensor
  humidity_sensor: humidity_sensor
  vpd_sensor: vpd_sensor
  co2_high_threshold: 1500
  co2_low_threshold: 800
  temp_high_threshold: 30
  temp_low_threshold: 18
  humidity_high_threshold: 70
  humidity_low_threshold: 40
  vpd_high_threshold: 1.5
  vpd_low_threshold: 0.4
  co2_high_alert:
    name: "CO2 High Alert"
    id: co2_high_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 30
  co2_low_alert:
    name: "CO2 Low Alert"
    id: co2_low_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 40
  temp_high_alert:
    name: "Temperature High Alert"
    id: temp_high_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 50
  temp_low_alert:
    name: "Temperature Low Alert"
    id: temp_low_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 60
  humidity_high_alert:
    name: "Humidity High Alert"
    id: humidity_high_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 70
  humidity_low_alert:
    name: "Humidity Low Alert"
    id: humidity_low_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 80
  vpd_high_alert:
    name: "VPD High Alert"
    id: vpd_high_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 90
  vpd_low_alert:
    name: "VPD Low Alert"
    id: vpd_low_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 100
  co2_high_threshold_number:
    name: "CO2 High Threshold"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 10
  co2_low_threshold_number:
    name: "CO2 Low Threshold"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 20
  temp_high_threshold_number:
    name: "Temperature High Threshold"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 25
  temp_low_threshold_number:
    name: "Temperature Low Threshold"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 35
  humidity_high_threshold_number:
    name: "Humidity High Threshold"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 45
  humidity_low_threshold_number:
    name: "Humidity Low Threshold"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 55
  vpd_high_threshold_number:
    name: "VPD High Threshold"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 65
  vpd_low_threshold_number:
    name: "VPD Low Threshold"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 75

number:
  - platform: template
    name: "Dummy Template Number"
    id: dummy_template_number
    min_value: 0
    max_value: 1
    step: 1
    optimistic: true
    internal: true

select:
  - platform: template
    name: "Dummy Template Select"
    id: dummy_template_select
    options:
      - "Option 1"
      - "Option 2"
    optimistic: true
    internal: true

switch:
  - platform: template
    name: "Dummy Template Switch"
    id: dummy_template_switch
    optimistic: true
    internal: true

binary_sensor:
  # Light validation - hardware detection only
  - platform: gpio
    pin:
      number: 9 # Port B digital pin on M5Stack Core S3
      mode: INPUT_PULLDOWN
      inverted: true
    name: "Grow Light On"
    id: grow_light_on
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 35
    filters:
      - delayed_on: 5s # Debounce for startup
      - delayed_off: 10s # Debounce for shutdown

  # Grow light switch status from Home Assistant
  - platform: homeassistant
    name: "Grow Light Switch"
    id: grow_light_switch
    entity_id: switch.spider_farmer_sf600

  # Light validation alert - triggers when lights should be on but aren't
  - platform: template
    name: "Light Validation Alert"
    id: light_validation_alert
    lambda: |-
      return id(grow_light_switch).state && !id(grow_light_on).state;
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 110
    filters:
      - delayed_on: 60s # wait a minute before checking to avoid false positives
      - delayed_off: 60s

# Control buttons
button:
  - platform: restart
    name: "Restart"
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 60

  - platform: template
    name: "Log AXP2101 Diagnostics"
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 70
    on_press:
      - m5cores3_power.log_axp2101_diagnostics:
          component_id: m5_power

text_sensor:
  - platform: template
    name: "System Status"
    id: system_status
    lambda: |-
      std::string status = "Normal";
      if (id(co2_high_alert).state || id(co2_low_alert).state ||
          id(temp_high_alert).state || id(temp_low_alert).state ||
          id(vpd_high_alert).state || id(vpd_low_alert).state) {
        status = "Alert";
      }
      return status;
    update_interval: 10s
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 80

  - platform: wifi_info
    ip_address:
      name: "IP Address"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 90
    mac_address:
      name: "MAC Address"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 100
