substitutions:
  devicename: grow-tent-monitor
  hostname: grow-tent-monitor
  friendlyname: "Grow Tent Monitor"
  board: esp32-s3-devkitc-1
  framework_type: arduino
  api_encryption_key: !secret api_encryption_key
  ota_password: !secret ota_update_key

esphome:
  name: ${hostname}
  friendly_name: ${friendlyname}
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
    board_build.f_cpu: 240000000L
  libraries:
    - Wire
    - FS
    - SPIFFS
    - m5stack/M5Unified
    - m5stack/M5Utility@0.0.3
    - m5stack/M5GFX

external_components:
  - source:
      type: local
      path: ../my_components
    components:
      - grow_env_monitor
      - m5cores3_display
      - m5cores3_touch
      - board_m5cores3
      - m5cores3_power
      - scd4x_stats
      - scd4x_alerts

esp32:
  board: ${board}
  flash_size: 16MB
  framework:
    type: ${framework_type}

logger:
  level: WARN

debug:
  update_interval: 30s

api:
  encryption:
    key: "${api_encryption_key}"

ota:
  - platform: esphome
    password: "${ota_password}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  passive_scan: false
  power_save_mode: none
  ap:
    ssid: "Grow-Tent-Monitor"
    password: !secret fallback_hotspot_key

captive_portal:
web_server:
  version: 3
  port: 80
  sorting_groups:
    - id: environmental_monitoring
      name: "Environmental Monitoring"
      sorting_weight: 10
    - id: thermal_camera
      name: "Thermal Camera"
      sorting_weight: 20
    - id: environmental_alerts
      name: "Environmental Alerts"
      sorting_weight: 30
    - id: diagnostics
      name: "Diagnostics"
      sorting_weight: 40

i2c:
  sda: 2
  scl: 1
  scan: true

# Time synchronization with HA
time:
  - platform: homeassistant
    id: homeassistant_time

globals: []

# M5 Stack Hardware Support
board_m5cores3:
  id: m5_board

m5cores3_power:
  id: m5_power
  battery_sensor:
    name: "Battery Level"
    id: battery_level
  battery_present_sensor:
    name: "Battery Present"
    id: battery_present
  battery_charging_sensor:
    name: "Battery Charging"
    id: battery_charging

grow_env_monitor:
  id: grow_monitor
  display_brightness: 70
  display_rotation: 3
  thermal_camera:
    thermal_refresh_rate: "16Hz" # Higher performance testing
    thermal_resolution: "18-bit" # Good balance of precision/speed
    thermal_pattern: "chess" # Better for even temperature distribution
    thermal_palette: "ironblack" # Most intuitive color mapping
    thermal_single_frame: true
  sensors:
    co2: co2_sensor
    temperature: temperature_sensor
    humidity: humidity_sensor
    thermal_min: mlx_min_temp
    thermal_max: mlx_max_temp
    thermal_avg: mlx_mean_temp
    light_sensor: grow_light_on
# M5 Stack Touch Support
m5cores3_touch:
  id: m5_touch
  on_touch:
    - logger.log:
        format: "Touch detected at (%d, %d)"
        args: ["touch.x", "touch.y"]
  on_release:
    - logger.log: "Touch released"
# End M5 Stack Hardware Support

sensor:
  - platform: scd4x
    id: co2_component
    co2:
      name: "CO2"
      id: co2_sensor
      web_server:
        sorting_group_id: environmental_monitoring
        sorting_weight: 10
    temperature:
      name: "Temperature"
      id: temperature_sensor
      web_server:
        sorting_group_id: environmental_monitoring
        sorting_weight: 20
    humidity:
      name: "Humidity"
      id: humidity_sensor
      web_server:
        sorting_group_id: environmental_monitoring
        sorting_weight: 30

  # MLX90640 Thermal Camera - real sensors are defined below as mlx_min_temp, mlx_max_temp, mlx_mean_temp

  # System monitoring
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    update_interval: 60s
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 10

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 20

  # Debug/Performance monitoring
  - platform: debug
    free:
      name: "Free Memory"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 30
    block:
      name: "Heap Block Size"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 40
    loop_time:
      name: "Loop Time"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 50

  # MLX90640 sensors - will be updated by grow_env_monitor component
  - platform: template
    name: "MLX90640 Min temp"
    id: mlx_min_temp
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    web_server:
      sorting_group_id: thermal_camera
      sorting_weight: 10
  - platform: template
    name: "MLX90640 Max temp"
    id: mlx_max_temp
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    web_server:
      sorting_group_id: thermal_camera
      sorting_weight: 20
  - platform: template
    name: "MLX90640 Mean temp"
    id: mlx_mean_temp
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
    web_server:
      sorting_group_id: thermal_camera
      sorting_weight: 30

scd4x_stats:
  id: co2_stats
  co2_sensor: co2_sensor
  temperature_sensor: temperature_sensor
  humidity_sensor: humidity_sensor
  time_id: homeassistant_time
  vpd:
    name: "VPD"
    id: vpd_sensor
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 40
  daily_max_co2:
    name: "Daily Max CO2"
    id: daily_max_co2
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 50
  daily_min_temp:
    name: "Daily Min Temperature"
    id: daily_min_temp
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 60
  daily_max_temp:
    name: "Daily Max Temperature"
    id: daily_max_temp
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 70
  co2_moving_avg:
    name: "CO2 Moving Average"
    id: co2_moving_avg
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 80
  temp_moving_avg:
    name: "Temperature Moving Average"
    id: temp_moving_avg
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 90

scd4x_alerts:
  id: co2_alerts
  co2_sensor: co2_sensor
  temperature_sensor: temperature_sensor
  humidity_sensor: humidity_sensor
  vpd_sensor: vpd_sensor
  co2_high_threshold: 1500
  co2_low_threshold: 800
  temp_high_threshold: 30
  temp_low_threshold: 18
  humidity_high_threshold: 70
  humidity_low_threshold: 40
  vpd_high_threshold: 1.5
  vpd_low_threshold: 0.4
  co2_high_alert:
    name: "CO2 High Alert"
    id: co2_high_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 30
  co2_low_alert:
    name: "CO2 Low Alert"
    id: co2_low_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 40
  temp_high_alert:
    name: "Temperature High Alert"
    id: temp_high_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 50
  temp_low_alert:
    name: "Temperature Low Alert"
    id: temp_low_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 60
  humidity_high_alert:
    name: "Humidity High Alert"
    id: humidity_high_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 70
  humidity_low_alert:
    name: "Humidity Low Alert"
    id: humidity_low_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 80
  vpd_high_alert:
    name: "VPD High Alert"
    id: vpd_high_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 90
  vpd_low_alert:
    name: "VPD Low Alert"
    id: vpd_low_alert
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 100

number:
  - platform: template
    name: "CO2 High Threshold"
    id: co2_high_threshold_number
    min_value: 500
    max_value: 2000
    step: 50
    initial_value: 1500
    optimistic: true
    unit_of_measurement: "ppm"
    icon: "mdi:molecule-co2"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 10
  - platform: template
    name: "CO2 Low Threshold"
    id: co2_low_threshold_number
    min_value: 400
    max_value: 1000
    step: 50
    initial_value: 800
    optimistic: true
    unit_of_measurement: "ppm"
    icon: "mdi:molecule-co2"
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 20
  - platform: template
    name: "Thermal Update Interval"
    id: thermal_update_interval_number
    min_value: 100
    max_value: 30000
    step: 100
    initial_value: 20000
    optimistic: true
    unit_of_measurement: "ms"
    icon: "mdi:timer"
    web_server:
      sorting_group_id: thermal_camera
      sorting_weight: 80
    on_value:
      - lambda: 'id(grow_monitor).update_thermal_interval(x);'

select:
  - platform: template
    name: "Thermal Color Palette"
    id: thermal_palette_select
    optimistic: true
    initial_option: "ironblack"
    options:
      - "rainbow"
      - "golden"
      - "grayscale"
      - "ironblack"
      - "cam"
      - "ironbow"
      - "arctic"
      - "lava"
      - "whitehot"
      - "blackhot"
    icon: "mdi:palette"
    web_server:
      sorting_group_id: thermal_camera
      sorting_weight: 40
    on_value:
      - lambda: 'id(grow_monitor).update_thermal_palette(x);'
  - platform: template
    name: "Thermal Refresh Rate"
    id: thermal_refresh_rate_select
    optimistic: true
    initial_option: "16Hz"
    options:
      - "0.5Hz"
      - "1Hz"
      - "2Hz"
      - "4Hz"
      - "8Hz"
      - "16Hz"
      - "32Hz"
      - "64Hz"
    icon: "mdi:camera-timer"
    web_server:
      sorting_group_id: thermal_camera
      sorting_weight: 50
    on_value:
      - lambda: 'id(grow_monitor).update_thermal_refresh_rate(x);'
  - platform: template
    name: "Thermal Pattern"
    id: thermal_pattern_select
    optimistic: true
    initial_option: "chess"
    options:
      - "chess"
      - "interleaved"
    icon: "mdi:grid"
    web_server:
      sorting_group_id: thermal_camera
      sorting_weight: 60
    on_value:
      - lambda: 'id(grow_monitor).update_thermal_pattern(x);'

switch:
  - platform: template
    name: "Thermal Single Frame"
    id: thermal_single_frame_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    icon: "mdi:camera-burst"
    web_server:
      sorting_group_id: thermal_camera
      sorting_weight: 70
    on_turn_on:
      - lambda: 'id(grow_monitor).update_thermal_single_frame(true);'
    on_turn_off:
      - lambda: 'id(grow_monitor).update_thermal_single_frame(false);'

binary_sensor:
  # Light validation - hardware detection only
  - platform: gpio
    pin:
      number: 9 # Port B digital pin on M5Stack Core S3
      mode: INPUT_PULLDOWN
      inverted: true
    name: "Grow Light On"
    id: grow_light_on
    web_server:
      sorting_group_id: environmental_monitoring
      sorting_weight: 35
    filters:
      - delayed_on: 5s # Debounce for startup
      - delayed_off: 10s # Debounce for shutdown

  # Grow light switch status from Home Assistant
  - platform: homeassistant
    name: "Grow Light Switch"
    id: grow_light_switch
    entity_id: switch.spider_farmer_sf600

  # Light validation alert - triggers when lights should be on but aren't
  - platform: template
    name: "Light Validation Alert"
    id: light_validation_alert
    lambda: |-
      return id(grow_light_switch).state && !id(grow_light_on).state;
    web_server:
      sorting_group_id: environmental_alerts
      sorting_weight: 110
    filters:
      - delayed_on: 60s # wait a minute before checking to avoid false positives
      - delayed_off: 60s

# Control buttons
button:
  - platform: restart
    name: "Restart"
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 60

  - platform: template
    name: "Log AXP2101 Diagnostics"
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 70
    on_press:
      - m5cores3_power.log_axp2101_diagnostics:
          component_id: m5_power

text_sensor:
  - platform: template
    name: "System Status"
    id: system_status
    lambda: |-
      std::string status = "Normal";
      if (id(co2_high_alert).state || id(co2_low_alert).state ||
          id(temp_high_alert).state || id(temp_low_alert).state ||
          id(vpd_high_alert).state || id(vpd_low_alert).state) {
        status = "Alert";
      }
      return status;
    update_interval: 10s
    web_server:
      sorting_group_id: diagnostics
      sorting_weight: 80

  - platform: wifi_info
    ip_address:
      name: "IP Address"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 90
    mac_address:
      name: "MAC Address"
      web_server:
        sorting_group_id: diagnostics
        sorting_weight: 100
